//get daily breakdown
interface dailyBreakForGapOne {
  day: string;
  description:string[]
  whyToLearn:string[]
  revision: string
}

interface weeklyBrdeakdownGapOne {
  week: string;
  topic: string[];
  resources:string[];
  activities:string[];
  dailyBreakdown: dailyBreakForGapOne[]

}
//MCQs generated by Gemini alongside the study plan itself (single call), carried
//through the preview and sent back on save so they can be persisted to mcqtbl
export interface GeneratedMCQOptions {
  A: string;
  B: string;
  C: string;
  D: string;
}
export interface GeneratedMCQ {
  question: string;
  options: GeneratedMCQOptions;
  correctAns: string;
}

 export interface GoStudyPlanWeekGapOne {
  title: string;
  introduction: string;
  overallStrategy: string;
  weeklyBreakdown: weeklyBrdeakdownGapOne[];
  forNextTopic: string;
  finalReview: string;
  further: string;
  motivationMessage: string;
  mcqs?: GeneratedMCQ[];
}

//for gap of week 
//get  plan with gap of 4 days 
export interface weeklyBreakdownGapWeek {
    weekRange: string;
    topic: string ;
    description: string[];
    whyToLearn: string[];
    resources: string[];
    activities: string[];
} 

export interface GoStudyPlanGapFourDays {
    title : string;
    introduction: string;
    overallStrategy: string;
    weeklyBreakdown2: weeklyBreakdownGapWeek[];
    forNextTopic: string;
    finalReview: string;
    further: string;
    motivationMessage:string;
}

//get plan for a week 1- week2

export interface weeklyBreakdownForMoreWeek {
     weekRange: string;
    topic: string ;
    description: string[];
    whyToLearn: string[];
    resources: string[];
    activities: string[];
}

export interface GoStudyPlanGapWeek {
    title : string;
    introduction: string;
    overallStrategy: string;
    weeklyBreakdown3: weeklyBreakdownForMoreWeek[];
    forNextTopic: string;
    finalReview: string;
    further: string;
    motivationMessage: string;
}

//to get weekCount to show at descpription page 
export interface TotalWeekCount {
  count : number;
  title: string;
}

//to make week1, week2...... green color as it is compelted
export interface CompletedWeekPlan {
  completedWeeks: number;
  totalWeeks: number;
  testEnabled: boolean;
}


//to get mcq, one at a time
export interface MCQ {
  mcqID: number;
  mcq: string;
  // options: JSON,
  options: { [key: string]: string };

  isAttempted: boolean;
  // true once every MCQ for the plan has been attempted
  done: boolean;
  total: number;
  attempted: number;
}

//to show the post-quiz review: all MCQs colored correct/incorrect
export interface MCQReview {
  mcqID: number;
  mcq: string;
  options: { [key: string]: string };
  correctAns: string;
  optionSelected: string;
  isCorrect: boolean;
}